os:
- linux

env:
  matrix:
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh

script:
- python traviconda.py setup --url $MINICONDA_URL
- export PATH=/home/travis/miniconda/bin:$PATH

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
