env:
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

script:
- git version
- python condaci.py setup $PYTHON_VERSION

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
