os:
- linux

env:
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

script:
- python traviconda.py setup --python $PYTHON_VERSION
- echo $(python traviconda.py version)
- export PATH=/home/travis/miniconda/bin:$PATH

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
