build: false

environment:
  global:
    BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x86
- x64

install:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py' C:\\traviconda.py; echo "Done"
- cmd: python C:\\traviconda.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%
