build: false

environment:
  global:
    BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x86
- x64

install:
- git version
- python traviconda.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%
